# This workflow will curl the readthedocs.org API to trigger a build
# when a PR is merged in this repo

name: Build readthedocs

on:
  pull_request:
    types:
      - closed

env:
  READTHEDOCS_TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl \
          -X POST \
          -H "Authorization: Token ${READTHEDOCS_TOKEN}" \
          https://readthedocs.org/api/v3/projects/modelstore/versions/latest/builds/
